### ISSUE TITLE
Investigate how other conformance resources are created and validated

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-model-fhir#17]
Extensions, ValueSets, CodeableConcepts

**Comment by ShahimEssaid** [comment]
This is just an example of trying to load a CodeSystem with the current CLI. I copied a XML CodeSystem from my working branch into the project/profiles directory and ran the validator.

`
2019-09-17 10:50:04,871 - kf_model_fhir.loader - DEBUG - Reading resource file: /home/shahim/git/gh/kids-first/kf-model-fhir-load-conformance/project/profiles/Participant.json
2019-09-17 10:50:04,872 - kf_model_fhir.loader - DEBUG - Reading resource file: /home/shahim/git/gh/kids-first/kf-model-fhir-load-conformance/project/profiles/hwCodeSystem.xml
2019-09-17 10:50:04,872 - kf_model_fhir.loader - INFO - Converting content of .xml file /home/shahim/git/gh/kids-first/kf-model-fhir-load-conformance/project/profiles/hwCodeSystem.xml to json format ... 
2019-09-17 10:50:24,609 - kf_model_fhir.loader - DEBUG - Converted content:Unable to find image 'kidsfirstdrc/torinox:torinox-1.0.2' locally
torinox-1.0.2: Pulling from kidsfirstdrc/torinox
fc7181108d40: Pulling fs layer
2c86df27317f: Pulling fs layer
66dd687a6ad1: Pulling fs layer
090671a11187: Pulling fs layer
d60f9abaaea4: Pulling fs layer
090671a11187: Waiting
d60f9abaaea4: Waiting
66dd687a6ad1: Download complete
090671a11187: Verifying Checksum
090671a11187: Download complete
d60f9abaaea4: Verifying Checksum
d60f9abaaea4: Download complete
fc7181108d40: Verifying Checksum
fc7181108d40: Download complete
2c86df27317f: Verifying Checksum
2c86df27317f: Download complete
fc7181108d40: Pull complete
2c86df27317f: Pull complete
66dd687a6ad1: Pull complete
090671a11187: Pull complete
d60f9abaaea4: Pull complete
Digest: sha256:fdda61a8c9870202949eb5f73233fd879bad409f62cee57857de0c28824ba43d
Status: Downloaded newer image for kidsfirstdrc/torinox:torinox-1.0.2
{"resourceType":"CodeSystem","id":"hwCodeSystem","url":"http://kf/hwCodeSystem","status":"draft","content":"complete","concept":[{"code":"Hello"},{"code":"World"}]}

Traceback (most recent call last):
  File "/home/shahim/git/gh/kids-first/kf-model-fhir-load-conformance/venv/bin/fhirmodel", line 11, in <module>
    load_entry_point('kf-model-fhir', 'console_scripts', 'fhirmodel')()
  File "/home/shahim/git/gh/kids-first/kf-model-fhir-load-conformance/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahim/git/gh/kids-first/kf-model-fhir-load-conformance/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/shahim/git/gh/kids-first/kf-model-fhir-load-conformance/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/shahim/git/gh/kids-first/kf-model-fhir-load-conformance/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahim/git/gh/kids-first/kf-model-fhir-load-conformance/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/shahim/git/gh/kids-first/kf-model-fhir-load-conformance/kf_model_fhir/cli.py", line 61, in validate
    success = FhirValidator().validate(resource_type, data_path)
  File "/home/shahim/git/gh/kids-first/kf-model-fhir-load-conformance/kf_model_fhir/validation.py", line 65, in validate
    success, results = self.validate_profiles(data_path)
  File "/home/shahim/git/gh/kids-first/kf-model-fhir-load-conformance/kf_model_fhir/validation.py", line 112, in validate_profiles
    self.profiles = loader.load_resources(data_path)
  File "/home/shahim/git/gh/kids-first/kf-model-fhir-load-conformance/kf_model_fhir/loader.py", line 137, in load_resources
    resource_dict = read_resource_file(p)
  File "/home/shahim/git/gh/kids-first/kf-model-fhir-load-conformance/kf_model_fhir/loader.py", line 175, in read_resource_file
    resource = json.loads(resource_json_str)
  File "/home/shahim/.pyenv/versions/3.7.4/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/shahim/.pyenv/versions/3.7.4/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/shahim/.pyenv/versions/3.7.4/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by ShahimEssaid** [comment]
I will create a pull request with the setup to load conformance resources from an "importDirectlry" until the CLI is able to do this.

**Comment by znatty22** [comment]
Going to mark this as complete, since it was about investigation and learning.
